jobs:
  - template: ../../azure-pipelines/jobs/run-tests.yml
    parameters:
      serviceName: ci-shared-bundle
      testCommand: bash -c 'wait-for-it.sh --strict --timeout=120 mysql:3306 && composer ci'
